update

diff --git a/backend/Dockerfile b/backend/Dockerfile
--- a/backend/Dockerfile
+++ b/backend/Dockerfile
@@ -1,12 +1,22 @@
-# Этап сборки
 FROM node:20 AS build
 WORKDIR /app
 COPY package*.json ./
-RUN npm install
-COPY . .
-RUN npm run build
 
-# Этап запуска
+RUN rm -rf node_modules package-lock.json
+
+RUN npm install --include=dev
+
+RUN rm -rf node_modules/typescript node_modules/.bin/tsc
+RUN npm install typescript@latest --force --no-save
+
+RUN cat node_modules/typescript/bin/tsc || echo "TSC FILE EMPTY OR MISSING"
+
+RUN node node_modules/typescript/bin/tsc --version
+
+COPY . .
+
+RUN node node_modules/typescript/bin/tsc
+
 FROM node:20-slim
 WORKDIR /app
 COPY --from=build /app/dist ./dist
